// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/**
 * @title ERC5564Announcer
 * @author Example
 * @notice Announcement contract for ERC-5564 Stealth Addresses
 *
 * This contract allows senders to announce stealth payments.
 * Receivers can scan emitted events to detect payments.
 */
contract ERC5564Announcer {

    /**
     * @notice Emitted when a stealth payment is announced
     * 
     * @param schemeId ID of the stealth scheme used
     * @param stealthAddress Generated stealth address that received funds
     * @param caller Sender who triggered the announcement
     * @param ephemeralPubKey Ephemeral public key generated by sender
     * @param metadata Optional metadata (token address, amount, etc.)
     */
    event Announcement(
        uint256 indexed schemeId,
        address indexed stealthAddress,
        address indexed caller,
        bytes ephemeralPubKey,
        bytes metadata
    );

    /**
     * @notice Announces a stealth payment
     *
     * @param schemeId Stealth address scheme identifier
     * @param stealthAddress Stealth address that received funds
     * @param ephemeralPubKey Sender's ephemeral public key
     * @param metadata Additional metadata
     */
    function announce(
        uint256 schemeId,
        address stealthAddress,
        bytes calldata ephemeralPubKey,
        bytes calldata metadata
    ) external {

        emit Announcement(
            schemeId,
            stealthAddress,
            msg.sender,
            ephemeralPubKey,
            metadata
        );
    }
}